<a href="https://colab.research.google.com/github/JohnNinan117/pyTorch/blob/main/Intro_to_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.4.1+cu121'

In [2]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
# Checking the number of dimensions
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
# Creating a random tensor of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor,random_tensor.dtype

(tensor([[0.2237, 0.2213, 0.9504, 0.5935],
         [0.1420, 0.2717, 0.8272, 0.9393],
         [0.0922, 0.4583, 0.9428, 0.4373]]),
 torch.float32)

In [15]:
# Creating a random tensor of size (224,224,3)
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [16]:
# Create a value from 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)

In [17]:
#  Creating a tensor with the same shape as another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0,6.0,9.0])
dtype = None
device = None
requires_grad = False
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [19]:
float_16_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [19]:
# Creating an example Tensor
ex_tensor = torch.rand(3,4)